# Generated by Django 4.2 on 2023-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pro_id',
            field=models.CharField(default=948, max_length=20),
        ),
    ]
